version: '3'
services:
  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - scrumpy-backend
  app:
    build: .
    env_file:
    - .env
    ports:
    - 8080:8080
    networks:
    - scrumpy-backend

networks:
  scrumpy-backend: